os: linux
dist: bionic
language: shell

services:
  - docker

env:
  global:
  - EMACS_IMAGE="pfitaxel/emacs-learn-ocaml-client"
  jobs:
  - LEARNOCAML_IMAGE="ocamlsf/learn-ocaml" LEARNOCAML_VERSION="0.12"
  - LEARNOCAML_IMAGE="pfitaxel/learn-ocaml" LEARNOCAML_VERSION="oauth-moodle-dev" USE_PASSWD="true"

install:
- docker pull "$LEARNOCAML_IMAGE:$LEARNOCAML_VERSION"
- docker pull "$EMACS_IMAGE:$LEARNOCAML_VERSION"

script:
- echo -e "${ANSI_YELLOW}Executing tests... ${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- ./test.sh
- echo -en 'travis_fold:end:script\\r'
